### PR TITLE
Fix youtube.lua crash

### PR DESCRIPTION
**Pull request by CheatCoder**
Sry for this little bug =)

### CODE REVIEW

**Comment by ShittyAdvice** [comment]
Seems unnecessary?

**Comment by ShittyAdvice** [comment]
Nvm, thanks

**Comment by CheatCoder** [comment]
I have see this issue youtube.lua would access send_youtube_data(data, receiver, link) but in youtube.lua is the link para not needed so i added the 1 to the Function and youtube.lua use the function without the link para =)

**Comment by ShittyAdvice** [comment]
I found that out ye, thanks

**Pull request merged**
